import type { SeedMeal } from '../types';

export const SEED_MEALS: SeedMeal[] = [
  { id: 'carbonara', name: 'Carbonara', ingredients: ['pâte', 'oeuf', 'lardons', 'parmesan', 'poivre'], illustration_key: 'carbonara', prep_minutes: 20 },
  { id: 'ratatouille', name: 'Ratatouille', ingredients: ['courgette', 'aubergine', 'tomate', 'poivron', 'oignon', 'ail', 'huile olive'], illustration_key: 'ratatouille', prep_minutes: 60 },
  { id: 'poulet-roti', name: 'Poulet rôti', ingredients: ['poulet', 'ail', 'citron', 'thym', 'beurre', 'huile olive'], illustration_key: 'poulet-roti', prep_minutes: 90 },
  { id: 'boeuf-bourguignon', name: 'Bœuf bourguignon', ingredients: ['boeuf', 'vin rouge', 'carotte', 'oignon', 'champignon', 'lardons', 'farine'], illustration_key: 'boeuf-bourguignon', prep_minutes: 150 },
  { id: 'quiche-lorraine', name: 'Quiche lorraine', ingredients: ['pâte brisée', 'oeuf', 'crème fraîche', 'lardons', 'gruyère'], illustration_key: 'quiche-lorraine', prep_minutes: 45 },
  { id: 'omelette', name: 'Omelette', ingredients: ['oeuf', 'beurre', 'sel', 'poivre'], illustration_key: 'omelette', prep_minutes: 10 },
  { id: 'soupe-legumes', name: 'Soupe de légumes', ingredients: ['carotte', 'poireau', 'pomme de terre', 'oignon', 'bouillon'], illustration_key: 'soupe-legumes', prep_minutes: 40 },
  { id: 'gratin-dauphinois', name: 'Gratin dauphinois', ingredients: ['pomme de terre', 'crème fraîche', 'ail', 'gruyère', 'beurre'], illustration_key: 'gratin-dauphinois', prep_minutes: 70 },
  { id: 'tarte-flambee', name: 'Tarte flambée', ingredients: ['pâte', 'crème fraîche', 'oignon', 'lardons'], illustration_key: 'tarte-flambee', prep_minutes: 25 },
  { id: 'risotto', name: 'Risotto', ingredients: ['riz arborio', 'bouillon', 'oignon', 'parmesan', 'beurre', 'vin blanc'], illustration_key: 'risotto', prep_minutes: 35 },
  { id: 'curry-poulet', name: 'Curry de poulet', ingredients: ['poulet', 'lait de coco', 'tomate', 'oignon', 'curry', 'ail', 'gingembre'], illustration_key: 'curry-poulet', prep_minutes: 40 },
  { id: 'bolognaise', name: 'Bolognaise', ingredients: ['boeuf haché', 'tomate', 'oignon', 'ail', 'carotte', 'pâte', 'vin rouge'], illustration_key: 'bolognaise', prep_minutes: 60 },
  { id: 'salade-nicoise', name: 'Salade niçoise', ingredients: ['thon', 'tomate', 'oeuf', 'haricot vert', 'olive', 'anchois'], illustration_key: 'salade-nicoise', prep_minutes: 20 },
  { id: 'croque-monsieur', name: 'Croque-monsieur', ingredients: ['pain de mie', 'jambon', 'gruyère', 'beurre', 'béchamel'], illustration_key: 'croque-monsieur', prep_minutes: 15 },
  { id: 'tarte-poireaux', name: 'Tarte aux poireaux', ingredients: ['pâte brisée', 'poireau', 'crème fraîche', 'oeuf', 'gruyère'], illustration_key: 'tarte-poireaux', prep_minutes: 50 },
  { id: 'poulet-citron', name: 'Poulet au citron', ingredients: ['poulet', 'citron', 'ail', 'thym', 'huile olive', 'miel'], illustration_key: 'poulet-citron', prep_minutes: 45 },
  { id: 'poisson-vapeur', name: 'Poisson vapeur', ingredients: ['poisson blanc', 'citron', 'herbe', 'sel', 'poivre'], illustration_key: 'poisson-vapeur', prep_minutes: 20 },
  { id: 'pates-pesto', name: 'Pâtes au pesto', ingredients: ['pâte', 'pesto', 'parmesan', 'basilic'], illustration_key: 'pates-pesto', prep_minutes: 15 },
  { id: 'chili-con-carne', name: 'Chili con carne', ingredients: ['boeuf haché', 'haricot rouge', 'tomate', 'oignon', 'poivron', 'cumin', 'piment'], illustration_key: 'chili-con-carne', prep_minutes: 50 },
  { id: 'soupe-potiron', name: 'Soupe de potiron', ingredients: ['potiron', 'oignon', 'crème fraîche', 'bouillon', 'noix de muscade'], illustration_key: 'soupe-potiron', prep_minutes: 40 },
  { id: 'boeuf-stroganov', name: 'Bœuf Stroganov', ingredients: ['boeuf', 'champignon', 'oignon', 'crème fraîche', 'moutarde', 'beurre'], illustration_key: 'boeuf-stroganov', prep_minutes: 30 },
  { id: 'crepes', name: 'Crêpes', ingredients: ['farine', 'oeuf', 'lait', 'beurre', 'sucre'], illustration_key: 'crepes', prep_minutes: 30 },
  { id: 'tian-legumes', name: 'Tian de légumes', ingredients: ['courgette', 'tomate', 'aubergine', 'oignon', 'thym', 'huile olive'], illustration_key: 'tian-legumes', prep_minutes: 60 },
  { id: 'poulet-champignons', name: 'Poulet aux champignons', ingredients: ['poulet', 'champignon', 'crème fraîche', 'oignon', 'ail', 'vin blanc'], illustration_key: 'poulet-champignons', prep_minutes: 40 },
  { id: 'lasagnes', name: 'Lasagnes', ingredients: ['pâte à lasagne', 'boeuf haché', 'tomate', 'béchamel', 'gruyère', 'oignon'], illustration_key: 'lasagnes', prep_minutes: 70 },
  { id: 'tarte-tatin', name: 'Tarte tatin', ingredients: ['pomme', 'pâte feuilletée', 'beurre', 'sucre', 'cannelle'], illustration_key: 'tarte-tatin', prep_minutes: 45 },
  { id: 'brandade', name: 'Brandade de morue', ingredients: ['morue', 'pomme de terre', 'ail', 'huile olive', 'crème'], illustration_key: 'brandade', prep_minutes: 50 },
  { id: 'paella', name: 'Paella', ingredients: ['riz', 'poulet', 'crevette', 'moule', 'poivron', 'tomate', 'safran', 'chorizo'], illustration_key: 'paella', prep_minutes: 60 },
  { id: 'blanquette-veau', name: 'Blanquette de veau', ingredients: ['veau', 'carotte', 'champignon', 'crème fraîche', 'oignon', 'oeuf', 'citron'], illustration_key: 'blanquette-veau', prep_minutes: 90 },
  { id: 'gateau-chocolat', name: 'Gâteau au chocolat', ingredients: ['chocolat', 'beurre', 'oeuf', 'farine', 'sucre'], illustration_key: 'gateau-chocolat', prep_minutes: 40 },
];
